#!/bin/bash

REPORT_PATH="$PWD/reports/html-report/index.html"

if [ ! -f "$REPORT_PATH" ]; then
  echo "  >> Relatorio nao existe. execute ./gradlew relatorio"
  exit 1
fi

if [ "$(uname)" = "Darwin" ]; then
  open ${REPORT_PATH}
else
  xdg-open ${REPORT_PATH}
fi
